/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parking_lot;

import java.io.InputStream;
import java.util.Scanner;

public class App {
	public static String delimiter = " ";
	
    public String getGreeting() {
    	return "hello world";
    }
	
	public String[] parseCommand(final String Line) {
        final String[] result = Line.split(delimiter);
        return result;
    }

    private Scanner mScanner;

    public void initScanner(String input) {
        mScanner = new Scanner(input);        
    }

    public void initScanner(InputStream input) {
    	mScanner = new Scanner(input);
    }
    
    public boolean hasCommandArgs() {
        if (mScanner != null)
            return mScanner.hasNextLine();
        else
            return false;
    }

    public String[] nextCommandArgs() {
        String line;
        if (mScanner != null)
            line = mScanner.nextLine();
        else
            line = "";
        String[] cmdArgs = line.split(" ");
        return cmdArgs;
    }

    public static void main(final String[] args) {

        final App commandlineParser = new App();

        if (args.length == 0) {
        	commandlineParser.initScanner(System.in);
        } else {
            final String filename = args[0];
            commandlineParser.initScanner(filename);
        }

        while (commandlineParser.hasCommandArgs()) {
            final String[] commandArgs = commandlineParser.nextCommandArgs();
            
            System.out.println("Command: " + commandArgs[0]);
        }
    }

}
